# This files provides an easy way to start Redis and PostgreSQL servers for
# development, via docker-compose.
# See doc/dev/getting-started/quickstart_6_start_server.md for how to
# use it.
#
# You can also use `sg run redis-postgres`.
services:
  redis:
    image: redis:6.2.5
    command: redis-server redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/data/redis.conf
      - ${REDIS_DATA_DIR:-redis_data}:/data
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${PGUSER:-sourcegraph}
      - POSTGRES_USER=${PGPASSWORD:-sourcegraph}
      - "POSTGRES_INITDB_ARGS= --encoding=UTF8 "
    volumes:
      - ${PGDATA_DIR:-postgres_data}:/var/lib/postgresql/data
volumes:
  redis_data:
  postgres_data:
